---
# tasks file for ec2

- name: Create ec2 instance
  amazon.aws.ec2_instance:
    name: "{{ item.name }}"
    key_name: "{{ key_name_aws }}"
    # vpc_subnet_id: we are using default vpc
    instance_type: "{{ type }}"
    security_group: default
    region: "{{ proj3_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    network:
      assign_public_ip: true
    image_id: "{{ item.image }}"
    tags:
      Environment: "{{ item.name }}"
      Project: "AWS-Configuration-Management"
  loop:
    - {image: "{{ ubuntu_ami }}", name: "ansible-ubun-01"}
    - {image: "{{ ubuntu_ami }}", name: "ansible-ubun-02"}
    - {image: "{{ amazon_linux_ami }}", name: "ansible-amlin-03"}