---
- name: Apply SSH configuration changes on EC2 instance
  hosts: localhost
  gather_facts: no
  become: yes

  vars_prompt:
    - name: "public_ip"
      prompt: "Enter the EC2 instance public IP"
      private: no

  tasks:
    - name: Add EC2 instance to inventory
      add_host:
        name: "{{ public_ip }}"
        ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
        ansible_user: "{{ ansible_user }}"

- name: Configure SSH on EC2 instance
  hosts: "{{ public_ip }}"
  become: yes

  roles:
    - passwordless_authentication
