---
# tasks file for passwordless_authenticator
- name: Ensure SSH Password Authentication is Enabled
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'
    create: yes
  notify: Restart SSH

- name: Set the user password
  become: true
  user:
    name: "{{ ec2_username }}"
    password: "{{ password }}"

- name: Restart SSH
  become: true
  systemd:
    name: ssh
    state: restarted

- name: Copy SSH key to EC2 instance
  become: false
  command: "ssh-copy-id -i {{ keypem_location }} {{ ec2_username }}@{{ public_ip }}"
