---
# tasks file for passwordless-authenticator
---
- name: Ensure PasswordAuthentication is set to yes
  ansible.builtin.lineinfile:
    path: /etc/ssh/60-cloudimg-settings.conf
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'
    state: present
    backup: yes

- name: Restart SSH service
  ansible.builtin.systemd:
    name: ssh
    state: restarted
    enabled: yes

- name: Set user password
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ 'password' | password_hash('sha512') }}"
