---
- name: Ensure PasswordAuthentication is set to yes
  lineinfile:
    path: "/etc/ssh/sshd_config.d/60-cloudimg-settings.conf"
    regexp: '^#?PasswordAuthentication\s+no'
    line: 'PasswordAuthentication yes'
    state: present
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Restart SSH service to apply configuration changes
  service:
    name: sshd
    state: restarted

- name: Set password for the ubuntu user
  expect:
    command: passwd {{ ansible_user }}
    responses:
      'Enter new UNIX password:': "YOUR_PASSWORD\n"
      'Retype new UNIX password:': "YOUR_PASSWORD\n"
    echo: yes

- name: Use ssh-copy-id to copy SSH key to the EC2 instance
  delegate_to: localhost
  shell: ssh-copy-id -i ~/.ssh/id_rsa.pub {{ ansible_user }}@{{ public_ip }}
  ignore_errors: true

- name: Verify passwordless SSH access
  command: ssh {{ ansible_user }}@{{ public_ip }} hostname
